### ISSUE TITLE
Lightpath opens extra PyDM Main Window

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lightpath#112]
## Expected Behavior

Should not spawn an empty main window

## Current Behavior

Extra main window loaded
![image](https://user-images.githubusercontent.com/10647860/88083433-e1ca6900-cb37-11ea-9a17-777931dbaa6b.png)

## Possible Solution

Read PyDM docs and update lightpath code

## Steps to Reproduce (for bugs)

1. Open lightpath UI

## Context

If it annoys me, it will annoy users

## Your Environment

Latest

**Comment by hhslepicka** [comment]
The culprit is the launcher script at `/bin/lightpath`.
At this line here it creates a PyDMApplication (https://github.com/pcdshub/lightpath/blob/master/bin/lightpath#L27) and since probably this code is old and predates the work to no longer depend on the PyDMApplication & PyDMMainWindow it does this.

Simply using the `use_main_window=False` option at the PyDMApplication constructor should address this issue. More info here: https://github.com/slaclab/pydm/blob/master/pydm/application.py#L77

**Comment by ZLLentz** [comment]
Thank you Hugo! I figured it was something like that. This launcher is very very old. I'll made the appropriate change.
